server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location /app-dev/ {
        try_files $uri $uri/ /app-dev/index.html;
    }

    location = /app-dev {
        return 301 /app-dev/;
    }

    location /cinema/ {
        try_files $uri $uri/ /cinema/index.html;
    }

    location = /cinema {
        return 301 /cinema/;
    }
}
