server {
    listen 80;
    server_name _;

    location /app-dev/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /app-dev/index.html;
    }

    location /app-dev {
        return 301 /app-dev/;
    }
}
